#!/bin/bash
# open: Open application/file/folder in Windows from CYGWIN shell.
# 
# Copyright (C) 2014, Arlen Liu
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# (http://arlen.cn)


cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
esac

if [ "$1" = "" ]; then
  path=. 
else
  path=$1
fi

if $cygwin; then
  path=`cygpath -C ANSI -aw "$path"`
fi

explorer $path
